name = "still-haze-01c8"
main = "src/index.js"
compatibility_date = "2026-01-12"

routes = [
  { pattern = "greenwood-pizzeria.com/api/*", zone_name = "greenwood-pizzeria.com" },
  { pattern = "greenwood-pizzeria.com/img/*", zone_name = "greenwood-pizzeria.com" }
]